export default {
  'tiny-mobile-button-height': '44px',
  'tiny-mobile-button-font-size': '16px',
  'tiny-mobile-button-color': '#fff',
  'tiny-mobile-button-disabled-color': '#ddd',
  'tiny-mobile-button-default-color': '#666',
  'tiny-mobile-button-default-border-color': '#ccc',
  'tiny-mobile-button-default-bgcolor': '#fff',
  'tiny-mobile-button-primary-color': '#039be5',
  'tiny-mobile-button-success-color': '#52c41a',
  'tiny-mobile-button-warning-color': '#faad14',
  'tiny-mobile-button-danger-color': '#f04b3d',
  'tiny-mobile-button-info-color': '#333',
  'tiny-mobile-button-medium-height': '36px',
  'tiny-mobile-button-medium-font-size': '14px',
  'tiny-mobile-button-small-height': '30px',
  'tiny-mobile-button-small-font-size': '14px',
  'tiny-mobile-button-mini-height': '24px',
  'tiny-mobile-button-mini-font-size': '12px',
  'tiny-mobile-button-radius': '2px',
  'tiny-mobile-button-text-color': '#1890ff',
  'tiny-mobile-button-text-hover-color': '#40a9ff',
  'tiny-mobile-button-text-active-color': '#096dd9',
  'tiny-mobile-button-text-disabled-color': '#999'
}
