export default {
  'tiny-mobile-input-bgcolor': '#fff',
  'tiny-mobile-input-height': '30px',
  'tiny-mobile-input-medium-height': '42px',
  'tiny-mobile-input-small-height': '36px',
  'tiny-mobile-input-mini-height': '24px',
  'tiny-mobile-input-disabled-color': '#999',
  'tiny-mobile-input-disabled-bgcolor': '#f5f5f5',
  'tiny-mobile-input-exceed-color': '#f5222d',
  'tiny-mobile-input-icon-font-size': '16px',
  'tiny-mobile-input-icon-close-color': '#bfbfbf',
  'tiny-mobile-textarea-count-color': '#999',
  'tiny-mobile-textarea-count-font-size': '12px',
  'tiny-mobile-textarea-inner-height': '96px',
  'tiny-mobile-textarea-inner-font-size': '16px',
  'tiny-mobile-textarea-inner-color': '#666',
  'tiny-mobile-textarea-inner-placeholder-color': '#ccc',
  'tiny-mobile-textarea-title-font-size': '16px',
  'tiny-mobile-textarea-title-color': '#333',
  'tiny-mobile-textarea-showlimit-inner-height': '70px',
  'tiny-mobile-textarea-showcontent-inner-height': '66px'
}
